"""reading_progress per-user

Revision ID: 4f4d0c9088cc
Revises: 6e5b8d683f73
Create Date: 2026-04-25 11:48:37.026906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4d0c9088cc'
down_revision: Union[str, Sequence[str], None] = '6e5b8d683f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_reading_progress_book_user', ['book_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('fk_reading_progress_device_id_devices'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reading_progress_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_reading_progress_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reading_progress_device_id_devices'), 'devices', ['device_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_reading_progress_book_user', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
